/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.dream.api;

import io.swagger.annotations.Api;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-10-26T09:52:39.957Z")

@Api(value = "v1", description = "the v1 API", tags = { "统计" })
public interface StatisticV1Api {

}
